version: '3'

services:
  boilerplate-mochachai-api:
    build:
      context: ../..
      dockerfile: ./Dockerfile
      args:
        - CONTEXT_PATH=/boilerplate-mochachai
    ports:
      - 3000:3000
    environment:
      - CONTEXT_PATH=/boilerplate-mochachai
    restart: unless-stopped